# ansible-playbook -i hosts deploy.yaml
#docker build -t rust-api-date:1.0 .
# docker run -it rust-api-date:1.0
#docker run --publish 8080:8080 --detach --name rad rust-api-date:1.0

---
- name: Deploy all roles
  hosts: all
  become: true
  become_user: root
  tasks:
    - include: roles/docker/tasks/main.yml
    - include: roles/rust-date-api/tasks/main.yml
